Repository sonata-project/SonataIntlBundle, pull requests merged in 2019-05, with the labels that each got.

#254 Fixed fqcn
  docs/reference/installation.rst
Labels: docs

#257 Twig deprecation notice
  composer.json
  src/Twig/Extension/DateTimeExtension.php
  src/Twig/Extension/LocaleExtension.php
  src/Twig/Extension/NumberExtension.php
Labels: patch

#258 Accept currency value represented as string (issue #256)
  src/Templating/Helper/NumberHelper.php
  tests/Helper/NumberHelperTest.php
Labels: patch

#259 Leverage `display_datetime.html.twig` from `history_revision_timestamp.html.twig`
  src/Resources/views/CRUD/history_revision_timestamp.html.twig
Labels: minor
