Repository sonata-project/SonataIntlBundle, pull requests merged in 2021-08, with the labels that each got.

#430 Fix `NumberFormatter::format(): Argument #1 ($num) must be of type int|float, string given` (fixes #427)
  src/Templating/Helper/BaseHelper.php
  src/Templating/Helper/NumberHelper.php
  tests/Helper/NumberHelperTest.php
Labels: patch

#432 Bump dependency (and fix security issues)
  composer.json
Labels: pedantic

#448 Update doc url
  docs/reference/configuration.rst
Labels: docs
