Repository sonata-project/SonataIntlBundle, pull requests merged in 2022-08, with the labels that each got.

#535 Use DatetimeInterface in Formatter
  src/Helper/DateTimeFormatter.php
  src/Helper/DateTimeFormatterInterface.php
Labels: pedantic

#536 Fix psalm
  src/Helper/NumberFormatter.php
Labels: pedantic

#539 Add type hint and final keyword
  docs/reference/configuration.rst
  docs/reference/locale.rst
  docs/reference/number.rst
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataIntlExtension.php
  src/Helper/BaseHelper.php
  src/Helper/DateTimeFormatter.php
  src/Helper/DateTimeFormatterInterface.php
  src/Helper/NumberFormatter.php
  src/Helper/NumberFormatterInterface.php
  src/SonataIntlBundle.php
  src/Timezone/ChainTimezoneDetector.php
  src/Timezone/TimezoneAwareTrait.php
  src/Timezone/TimezoneDetectorInterface.php
  src/Timezone/UserBasedTimezoneDetector.php
  src/Twig/DateTimeRuntime.php
  src/Twig/Extension/DateTimeExtension.php
  src/Twig/Extension/LocaleExtension.php
  src/Twig/Extension/NumberExtension.php
  src/Twig/LocaleRuntime.php
  src/Twig/NumberRuntime.php
  tests/Helper/LocalizerTest.php
  tests/Twig/Extension/NumberRuntimeTest.php
Labels: major

#542 fix: Add missing kernel.local_aware tags for definitions that impleme…
  src/Resources/config/intl.php
Labels: patch

#547 Allow symfony/translation-contracts 3
  composer.json
Labels: feature
