Repository sonata-project/SonataIntlBundle, pull requests merged in 2023-12, with the labels that each got.

#595 Allow packages from "symfony/*" ^7
  .github/workflows/test.yaml
  composer.json
  src/DependencyInjection/Configuration.php
Labels: minor

#601 DevKit updates for 3.x branch
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#604 Fix PHPStan findings at `UserBasedTimezoneDetectorTest::testUserTimezoneDetection()`
  tests/Timezone/UserBasedTimezoneDetectorTest.php
Labels: pedantic

#602 DevKit updates
  .php-cs-fixer.dist.php
Labels: automerge, dev-kit

#603 DevKit updates
  .php-cs-fixer.dist.php
Labels: automerge, dev-kit
