Repository sonata-project/SonataIntlBundle, pull requests merged in 2024-06, with the labels that each got.

#613 Bump rector
  composer.json
Labels: pedantic

#614 DevKit updates for 3.x branch
  .github/workflows/documentation.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#615 Solve internal class usage
  src/DependencyInjection/SonataIntlExtension.php
Labels: patch
