Repository sonata-project/SonataIntlBundle, pull requests merged in 2025-05, with the labels that each got.

#628 DevKit updates for 4.x branch
  phpstan.neon.dist
Labels: automerge, dev-kit

#626 Fix `format_datetime` twig filter deprecation message
  src/Twig/Extension/DateTimeExtension.php
Labels: patch

#630 3.2.1
  CHANGELOG.md
Labels: pedantic

#631 DevKit updates for 3.x branch
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/test.yaml
  Makefile
Labels: automerge, dev-kit
